name: Latest CoreProtect Commit
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
  
  steps:
      - name: Checkout the repo
        uses: actions/checkout@v5
        with:
          fetch-depth: 1

      - name: Get commit
        id: commit
        run: |
          echo "sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
          echo "short_sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Update coreprotect latest
        run: |
          mkdir -p coreprotect
          echo "${{ steps.commit.outputs.short_sha }}" > coreprotect/latest.txt
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add coreprotect/latest.txt
          git commit -m "Update coreprotect latest to ${{ steps.commit.outputs.short_sha }}" || echo "No changes to commit"
          git push
      